drugorder_new/drugorder/client/urls.py
from django.conf.urls import include, url
from django.conf.urls import *
from django.contrib import admin
from .views import client_create,order_create,order_confirm,order_list,index,test_order,product_search,dautocomplete,completed_order,shopping_cart,recent_order,change_password
urlpatterns = [
    url(r'^$',index, name="home"),
    url(r'^change_password/$',change_password, name="change_password"),
    url(r'^recent_order/$',recent_order, name="recent_order"),
    url(r'^completed_order/$',completed_order, name="completed_order"),
    url(r'^order_history/$',order_list, name="order_history"),
    url(r'^shopping_cart/$', shopping_cart, name="shopping_cart"),
    url(r'^order_confirmation/$',order_confirm, name="order_confirm"),
    url(r'^client_form/$',client_create, name="client_form"),
    url(r'^make_order/$',order_create, name="make_order"),
    url(r'^test_order/$',test_order, name="test_order"),
    url(r'^product_search/$',product_search, name="product_search"),
    url(r'^dautocomplete/$',dautocomplete, name="dautocomplete"),
    url(r'^admin/', admin.site.urls)
]

drugorder_new/drugorder/drugorder/urls.py
from django.conf.urls import url,include
from django.conf.urls import *
from django.contrib import admin
from django.contrib.auth import views as auth_views
from client import views

urlpatterns = [
    url(r'^accounts/login/$', views.login_page, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^client/', include('client.urls',namespace="client")),
    url(r'^admin/', admin.site.urls),
]

drugorder_new/drugorder/client/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number =  models.CharField(max_length=256,blank=True,null=True)
    email =  models.CharField(max_length=256,blank=True,null=True)
    USER_TYPE_CHOICES = (
        ('Vendor', 'Customer'),
        ('Administrator', 'Administrator')
    )
    user_type = models.CharField(max_length=50, choices=USER_TYPE_CHOICES, default='Vendor')

    def __str__(self):
        return self.user.username

    def __unicode__(self):
        return self.user.username

# @receiver(post_save, sender=User)
# def create_or_update_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#     instance.profile.save()


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()



# class Client(models.Model):
#     client_name = models.CharField(max_length=1000,help_text="i.e. david")
#     phone_number= models.IntegerField(help_text="i.e. 7651111111")
#     contact_email= models.CharField(max_length=200,help_text="i.e. david@purdue.edu")
#     #login = models.ForeignKey(Login, blank=True, null=True)
#     def __str__(self):
#         return self.client_name
#     def __unicode__(self):
#         return self.client_name


class Order(models.Model):
    def __str__(self):
        return '%09d' % self.pk

    def __unicode__(self):
        return '%09d' % self.pk

    def get_order_number(self):  # for future generating order number
        return '%09d' % self.pk

        # associates to one Client table line

    client_obj = models.ForeignKey(User, blank=True, null=True)

    # order info
    # order_number = get_order_number()  # for future generating order number
    ORDER_STATUS_CHOICES = (
        ('new', 'Products Ordered'),
        ('filled', 'Order Filled'),
        ('remove', 'Taken Out of Inventory'),
        ('ready', 'Order Ready for Pick Up'),
        ('billing', 'Order Delivered'),
        ('complete', 'Billing Complete')
    )
    status = models.CharField(max_length=50, choices=ORDER_STATUS_CHOICES, default='new')
    comment = models.TextField(max_length=1000, default="If you have any comments, please add it here")
    date_time = models.DateTimeField(auto_now_add=True)

class Drug(models.Model):  # This is the Drug table for detailed drug info

    # class functions
    def __str__(self):
        return self.drug_brand + " - " + self.drug_name

    def __unicode__(self):
        return self.drug_brand + " - " + self.drug_name

    # associate to one Order table line
    order_obj = models.ForeignKey(Order, blank=True, null=True)

    # drug info
    brand = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    strength = models.CharField(max_length=50)
    quantity = models.IntegerField(default=0)

class Product(models.Model):
    brand = models.CharField(max_length=200, default="N/A")
    name = models.CharField(max_length=200)
    strength = models.CharField(max_length=50)
    price=models.CharField(max_length=50)
    CIN = models.IntegerField()
    description = models.CharField(max_length=2000, blank=True, null=True, help_text="description here")

    # class functions
    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class Wish_List(models.Model):
    client_obj_wish = models.ForeignKey(User, blank=True, null=True)
    wish_drug_name = models.CharField(max_length=200)
    wish_drug_brand = models.CharField(max_length=200)
    wish_drug_strength=models.CharField(max_length=50)
    wish_drug_price=models.CharField(max_length=50)

class Shopping_Cart(models.Model):
    client_obj_shopping = models.ForeignKey(User)
    shopping_drug_brand = models.CharField(max_length=200)
    shopping_drug_name = models.CharField(max_length=200)
    shopping_strength = models.CharField(max_length=50)
    shopping_quantity = models.IntegerField(default=0)

class Wish_To_Order(models.Model):
    client_obj_WTO = models.ForeignKey(User, blank=True, null=True)
    WTO_drug_name = models.CharField(max_length=200)
    WTO_drug_brand = models.CharField(max_length=200)
    WTO_drug_strength = models.CharField(max_length=50)

drugorder_new/drugorder/client/views.py
from django.shortcuts import render,redirect,get_object_or_404, HttpResponse
from django.http import HttpResponseRedirect,HttpResponse,QueryDict
from .models import Order,Drug,Wish_List,Shopping_Cart,Product,Wish_To_Order
from .models import Profile
from django.forms import formset_factory
from .forms import OrderForm,DrugForm,BaseDrugFormSet,Wish_ListForm
from django.urls import reverse
from django.contrib import messages
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm, UserCreationForm
from django.contrib.auth import update_session_auth_hash, login, authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import LoginForm
from django.contrib.auth.models import User
from django.db import models
import json

def login_page(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        error_message = ""
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)

            # If the user object is empty, no matching username and password were found
            if user is not None:
                #if user.is_active:
                    if user.profile.user_type == "Vendor":
                        auth_login(request, user)
                    # Redirect the user to their profile page
                        return redirect(reverse("client:home"))
                    else:
                        return HttpResponse("please go to: admin.p-ordering.tk")
                #else:
                #    error_message = "Your account is disabled"
            else:
                error_message = "Username or password incorrect"

                # The page is being loaded for the first time, so load a blank page
    else:
        form = LoginForm()
        error_message = ""
    return render(request, 'registration/login.html', {'form': form, 'error_message': error_message, })


@login_required
def index(request):
    user=request.user
    context = {'user':user}
    return render(request, 'homepage.html', context)

@login_required
def recent_order(request):
    count=0
    user=request.user
    saveList=[]
    orderList = Order.objects.filter(Q(client_obj=user) & (Q(status='new')|Q(status='filled')|Q(status='removed')|Q(status='ready')|Q(status='billing'))).order_by('date_time')
    for order in orderList:
        count=count+1
        drugList=Drug.objects.filter(order_obj=order).all()
        saveList.append([drugList,order])
    orderNum=count
    context = {'user': user, 'saveList': saveList, 'orderNum': orderNum}
    return render(request, 'recent_order.html', context)


@login_required
def completed_order(request):
    count=0
    user=request.user
    #user = Client.objects.order_by('-pk')[0]
    saveList=[]
    orderList = Order.objects.filter(Q(client_obj=user) & Q(status='complete')).order_by('date_time')
    for order in orderList:
        count=count+1
        drugList=Drug.objects.filter(order_obj=order).all()
        saveList.append([drugList,order])
    orderNum=count
    context = {'user': user, 'saveList': saveList, 'orderNum': orderNum}
    return render(request, 'complete_order.html', context)

def client_create(request):
    if request.method=='POST':
        form=ClientForm(request.POST)
        if form.is_valid():
            # instance=form.save(commit=False)
            # print(form.cleaned_data.get("client_name"))
            # print(form.cleaned_data.get("phone_number"))
            # print(form.cleaned_data.get("contact_email"))
            # instance.save()
            name = request.POST.get('client_name')
            phone = request.POST.get('phone_number')
            email = request.POST.get('contact_email')
            print(name)
            print(phone)
            print(email)
            client_obj=Client(client_name=name,phone_number=phone,contact_email=email)
            client_obj.save()
            #user = Client.objects.get(name)
            #user=client_obj
            #orderform=OrderForm()
            #context = {'user': user, 'orderform':orderform}
            #return order_create(request)
            messages.success(request, 'Form submission successful')
            #return HttpResponseRedirect(reverse('client:client_form'))
    else:
        form=ClientForm()

    context={"form":form}
    return render(request,"client_form.html",context)

def order_create(request):
    user=request.user
    #user = Client.objects.order_by('-pk')[0]
    if request.method == 'POST':
        orderform = OrderForm(request.POST)
        if orderform.is_valid():
            drug = request.POST.get('drug_name')
            brand = request.POST.get('drug_brand')
            quantity = request.POST.get('quantity')
            strength = request.POST.get('strength')
            doctor = request.POST.get('doctor_name')
            doctorEmail = request.POST.get('doctor_email')
            comment = request.POST.get('comment')
            order_obj = Order(drug_name=drug, drug_brand=brand, quantity=quantity, strength=strength, doctor_name=doctor, doctor_email=doctorEmail, comment=comment, client_obj=user)
            order_obj.save()
            return order_confirm(request)
    else:
        orderform = OrderForm()
    context = {'user': user, 'orderform':orderform}
    return render(request, 'make_order.html', context)

@login_required
def test_order(request):
    user=request.user
    #user = Client.objects.order_by('-pk')[0]
    DrugFormSet = formset_factory(DrugForm,formset=BaseDrugFormSet,extra=2) #min_num=4
    if request.method == 'POST':
        drugformset = DrugFormSet(request.POST)
        if  drugformset.is_valid():
            for drugform in drugformset:
                df = drugform.cleaned_data
                drug_name = df.get('shopping_drug_name')
                drug_brand = df.get('shopping_drug_brand')
                strength = df.get('shopping_strength')
                quantity = df.get('shopping_quantity')
                cart_obj = Shopping_Cart(shopping_drug_name=drug_name, shopping_drug_brand=drug_brand, shopping_strength=strength, shopping_quantity=quantity, client_obj_shopping=user)
                cart_obj.save()
            drugformset=DrugFormSet()
            w_t_os=Wish_To_Order.objects.filter(client_obj_WTO=user).all()
            for w_t_o in w_t_os:
                w_t_o.delete()
            messages.success(request, 'Order Submitted to Shopping Cart Successful!')

    else:
        wish_to_orders = Wish_To_Order.objects.filter(client_obj_WTO=user)
        wto_dictionary=[]
        for wto in wish_to_orders:
            wto_dictionary.append({'shopping_drug_name': wto.WTO_drug_name, 'shopping_drug_brand': wto.WTO_drug_brand, 'shopping_strength': wto.WTO_drug_strength, 'shopping_quantity': 1})
        drugformset = DrugFormSet(initial=wto_dictionary)
    context = {'user': user,  'drugformset':drugformset}
    return render(request, 'testorder.html', context)

def order_confirm(request):
    return render(request,'order_confirmation.html')

def order_list(request):
    user = Client.objects.order_by('-pk')[0]
    orderList= Order.objects.filter(client_obj=user).all()
    nested_list = []
    for i in range(0, len(orderList), 5):
        nested_list.append(orderList[i:i + 5])
    context = {'user': user,'nested_list': nested_list}
    return render(request, 'order_history.html', context)

@login_required
def product_search(request):
    flag=0
    user=request.user
    #user = Client.objects.order_by('-pk')[0]
    wishs = Wish_List.objects.filter(client_obj_wish=user).all()
    for drug in wishs:
        if request.GET.get(str(drug.pk)):
            WTO_object = Wish_To_Order(client_obj_WTO=user,WTO_drug_name=drug.wish_drug_name,WTO_drug_brand=drug.wish_drug_brand,WTO_drug_strength=drug.wish_drug_strength)
            WTO_object.save()
        if request.GET.get(drug.wish_drug_name):
            drug.delete()
    if request.method == 'POST':
        wishform = Wish_ListForm(request.POST)
        if wishform.is_valid():
            drug_name = request.POST.get('wish_drug_name')
            drugList = Product.objects.filter(name=drug_name).all()
            if not drugList:
                flag=1
                wishList = Wish_List.objects.filter(client_obj_wish=user).all()
                messages.success(request, 'Product Not Exist')
            else:
                wishList = Wish_List.objects.filter(client_obj_wish=user).all()
                for w in wishList:
                    if w.wish_drug_name==drug_name:
                        flag=1
                        wishList = Wish_List.objects.filter(client_obj_wish=user).all()
                        messages.success(request, 'Product Already in The Wish List')
            if flag==0 :
                for product in drugList:
                    brand = product.brand
                    strength=product.strength
                    ###price
                    wish_obj = Wish_List(wish_drug_name=product.name, wish_drug_brand=brand,wish_drug_strength=strength, client_obj_wish=user)
                    wish_obj.save()
                    wishList = Wish_List.objects.filter(client_obj_wish=user).all()
    else:
        wishList = Wish_List.objects.filter(client_obj_wish=user).all()
        wishform = Wish_ListForm()
    context = {'user': user, 'wishform': wishform, 'wishList':wishList}
    return render(request,'productsearch.html',context)

def dautocomplete(request):
    if request.is_ajax():
        q = request.GET.get('term')
        drugs = Product.objects.filter(name__icontains=q)
        results = []
        for product in drugs:
            drug_json = {}
            drug_json['id'] = product.brand

drugorder_new/drugorder/client/templates/base.html
<!DOCTYPE HTML>
<html>
<head>
  <meta charset= "UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width = device-width, initial-scale = 1">
  {% load static %}
  <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="http://s.codepen.io/assets/libs/modernizr.js" type="text/javascript"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  <title>{% block title_name %}{% endblock %}</title>
</head>
<body>
  <div class="page">

    <!--header-->

    <div class="header">
      <ul class="hello">
        <li> <a href="#"><h3>   &nbsp;&nbsp;&nbsp;Logout<h3></a></li>
        <li> <h3>Hello, Mr Example</h3></li>
      </ul>
    </div>

    <div class="biggerHeader">
      <img src="{% static 'img/pharmLogo.png' %}" width="200" height="100">
      <h1>Pharmacy Ordering System</h1>
    </div>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>


    <!-- End Header -->

    {% block body %}
    {% endblock %}

    <!-- footer-->

    <div class="panel panel-default">
      <div class="panel-body"></div>
      <div class="panel-footer col-sm-12 col-md-12 col-lg-12">
            <!-- links at the bottom of the page that redirect users who are lost -->
            <p> <a href="https://www.purdue.edu/rx/">Purdue University Retail Pharmacy</a> |
         <a href="http://www.purdue.edu/"> Purdue University </a> |
         <a href="https://www.pharmacy.purdue.edu/"> Purdue University College of Pharmacy </a> </p>
      </div>
    </div>


  </div>
</body>
</html>

drugorder_new/drugorder/client/templates/client_form.html
<!--DOCTYPE html -->
<html>
<body>
<h1>Client Information Form</h1>
<form method='post' action="{% url 'client:client_form' %}">{% csrf_token %}
{{form.as_p}}
<input type='submit' value='create client'/>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{% if message.tags %} {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <p>Click button to create a new client user.</p>
</form>
<a href="http://localhost:8000/client/make_order/">Go To Drug Order Page</a>
</body>
</html>

drugorder_new/drugorder/client/templates/productsearch.html
<!DOCTYPE HTML>
<html>
    <head>
    <meta charset= "UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width = device-width, initial-scale = 1">
    {% load static %}
        <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <!--<script src="http://s.codepen.io/assets/libs/modernizr.js" type="text/javascript"></script>-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  <!-- custom styles -->


        <!--<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />-->
         <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" type="text/css" media="all" />
        <!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js" type="text/javascript"></script>-->
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" type="text/javascript"></script>

        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"  media="all"/>

      <title>Product Search</title>
    </head>

<body>
  <!--header-->
    <div class="page">
  <div class="header">
  <ul class="hello">
    <li> <a href="{% url 'logout' %}"><h3>   &nbsp;&nbsp;&nbsp;Logout<h3></a></li>
    <li> <h3>Hello, {{user.username}}</h3></li>

</ul>
</div>


  <div class="biggerHeader">
    <a href="{% url 'client:home' %}"><img src="{% static 'img/pharmLogo.png' %}" width="200" height="100"></a>
    <h1>Pharmacy Ordering System</h1>
  </div>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <!--  <a class="navbar-brand" href="#">Pharmacy Ordering System</a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'client:home' %}">Introduction Page</a></li>
          <li class="active"><a href="{% url 'client:product_search' %}">Product Search</a></li>
        <li><a href="{% url 'client:test_order' %}">New Order Page</a></li>
          <li><a href="{% url 'client:shopping_cart' %}">Shopping Cart</a></li>
          <li><a href="{% url 'client:recent_order' %}"> Recent Order Status</a></li>
         <li><a href="{% url 'client:completed_order' %}">Completed Order</a></li>
      <!--  <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>-->
      </ul>
    </div>

  </div>
</nav>
<!-- End Header -->
<!--Page Content-->
<div class="welcome">
<h1>Product Search</h1>
<!--<div class="buttons">-->

      <!--<center>  <a href="#" class="btn btn-default btn-lg">-->
          <!--<span class="glyphicon glyphicon-plus-sign"></span> New Product-->
      <!--</a></center>-->
      <!--</div>-->
</div>

 <div class="wwform" align="center" id="wwform">
    <form method='post' action="">{% csrf_token %}
        <p><label for="id_wish_drug_name">Search For Product:</label>
    <input id="id_wish_drug_name" type="text" name="wish_drug_name" maxlength="100" required /></p>
    <!--{{wishform.as_p}}-->
<input type='submit' id='drugs' value='Put Into Wish List'/>
        {% if messages %}
        <ul class="messages">
        {% for message in messages %}
        <li>{% if message.tags %} {% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
      {% endif %}
</form>
</div>
<p></p>
        <p></p>
        <p></p>
<!--<center>-->
<!--<div class="search">-->
  <!--<div class="col-sm-offset-2 col-md-offset-2 col-lg-offset-2 col-sm-8 col-md-8 col-lg-8">-->
  <!--<div class="input-group">-->
          <!--&lt;!&ndash;<form method='post' action="">{% csrf_token %}&ndash;&gt;-->
                <!--&lt;!&ndash;{{wishform.as_p}}&ndash;&gt;-->
              <!--&lt;!&ndash;<input type="text" id='drugs' value='Put Into Wish List' class="form-control" aria-label="...">&ndash;&gt;-->
          <!--&lt;!&ndash;</form>&ndash;&gt;-->

       <!--<input type="text" class="form-control" aria-label="...">-->
       <!--<div class="input-group-btn">-->
         <!--<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search By <span class="caret"></span></button>-->
         <!--<ul class="dropdown-menu dropdown-menu-right">-->
           <!--<li><a href="#">Generic Name</a></li>-->
           <!--<li><a href="#">Brand Name</a></li>-->
           <!--<li><a href="#">CIN number</a></li>-->

         <!--</ul>-->
       <!--</div>&lt;!&ndash; /btn-group &ndash;&gt;-->
     <!--</div>&lt;!&ndash; /input-group &ndash;&gt;-->
   <!--</div>&lt;!&ndash; /.col-lg-6 &ndash;&gt;-->
 <!--</div>&lt;!&ndash; /.row &ndash;&gt;-->
<!--</center>-->




<div id="panel">
<div class="panel panel-default col-sm-8 col-md-8 col-lg-8">
  <div class="panel-heading">Wish List</div>
  <div class="panel-body">
  </div>
  <table class="table">
    <tr>
        <th>Generic Name</th>
        <th>Brand Name</th>
        <th>Strength</th>
        <th>CIN Number</th>
        <th>Price Per Unit</th>
        <th>Delete Product</th>
        <th>Add to New Order</th>
      </tr>
      {% for drug in wishList %}
      <div class="item">
      <tr>
         <td> <span class="revision" data-pk="{{drug.pk}}" data-name="wish_drug_name" data-type="text">{{drug.wish_drug_name}}</span></td>
          <td> <span class="revision" data-pk="{{drug.pk}}" data-name="wish_drug_brand" data-type="text">{{drug.wish_drug_brand}}</span></td>
          <td> <span class="revision" data-pk="{{drug.pk}}" data-name="wish_drug_strength" data-type="text">{{drug.wish_drug_strength}}</span></td>

        <!--<td>{{drug.wish_drug_name}}</td>-->
        <!--<td>{{drug.wish_drug_brand}}</td>-->
        <!--<td>{{drug.wish_drug_strength}}</td>-->
        <td>CIN #123456789</td>
        <td>$xx.xx</td>
        <!--<td><a href="edit.html" class="btn btn-default btn-sm">-->
            <!--<span class="glyphicon glyphicon-edit"></span>-->
        <!--</a></td>-->
         <td> <form action="#" method="get">
          <input type="submit" class="btn" value="Delete This Drug" name="{{drug.wish_drug_name}}">
          </form></td>

           <td> <form action="#" method="get">
          <input type="submit" class="btn" value="Add This Drug" name="{{drug.pk}}">
          </form></td>
      </tr>
      </div>
      {% endfor %}
    </table>
</div>
</div>


    <!--<div class="ui-widget">-->
  <!--<label for="drugs">Drug Search: </label>-->
  <!--<input id="drugs">-->
<!--</div>-->

<!--<form method='post' action="">{% csrf_token %}-->
    <!--{{wishform.as_p}}-->
<!--<input type='submit' id='drugs' value='Put Into Wish List'/>-->
<!--</form>-->

    <script type="text/javascript">
    $(document).ready(function(){
        var product_input=$('input[id="id_wish_drug_name"]');
        product_input.autocomplete({
          source: "{% url 'client:dautocomplete' %}",
          minLength: 2,
          position: { my : "right left", at: "right bottom" },
          appendTo: "#wwform"
        });
      } );

      jQuery.ui.autocomplete.prototype._resizeMenu = function () {
          var ul = this.menu.element;
          ul.outerWidth(this.element.outerWidth());
        }
    </script>

<!-- footer-->
<div class="panel panel-default">
  <div class="panel-body">

  </div>
  <div class="panel-footer col-sm-12 col-md-12 col-lg-12">
    <!-- links at the bottom of the page that redirect users who are lost -->
    <p> <a href="https://www.purdue.edu/rx/">Purdue University Retail Pharmacy</a> |
   <a href="http://www.purdue.edu/"> Purdue University </a> |
  <a href="https://www.pharmacy.purdue.edu/"> Purdue University College of Pharmacy </a> </p>
  </div>
</div>
</div>
</body>
</div>
</html>